plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/hoshi/Local Code/FINARTS/Assignments/Homework 2/deployment"
publishOrigin = "default"
base = "/Users/hoshi/Local Code/FINARTS/Assignments/Homework 2/deployment"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]